os:
    - linux
    - osx

language: java

jdk:
    - openjdk11

env:
    - GRAALVM_VERSION="21.2.0" GRAALVM_JAVA_VERSION="11" SL_BUILD_NATIVE="false"

matrix:
    exclude:
        - env: GRAALVM_VERSION="21.2.0" GRAALVM_JAVA_VERSION="11"
          jdk: openjdk11
          os: linux
        - jdk: openjdk11
          os: osx
          env: GRAALVM_VERSION="NONE" SL_BUILD_NATIVE="false"
cache:
  directories:
  - $HOME/.m2

before_install:
    - git clone https://github.com/streamblocks/streamblocks-tycho --depth 1 streamblocks-tycho
    - cd streamblocks-tycho
    - mvn -DskipTests install -pl '!app-test,!language-server,!platform-generic-c'
    - cd ../

install:
    - |
        if [[ "$GRAALVM_VERSION" != "NONE" ]]; then
          if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="darwin"; fi
          if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
          curl -LJ "https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java$GRAALVM_JAVA_VERSION-$DOWNLOAD_OS_NAME-amd64-$GRAALVM_VERSION.tar.gz" --output graalvm.tar.gz
          tar -xzf graalvm.tar.gz
          export JAVA_HOME="$(pwd)/graalvm-ce-java$GRAALVM_JAVA_VERSION-$GRAALVM_VERSION"
          if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
          "$JAVA_HOME/bin/gu" install native-image
        else
          if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
        fi



script:
    - if [[ "$GRAALVM_VERSION" != "NONE" ]]; then mvn test; fi
