# This workflow runs mvn package on the repository, and uploads the native image as artifact
name: Build Package and upload calnative
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        id: mavencache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Get GraalVM Version from pom.xml
        id: getgraalversion
        run: |
          echo "::set-output name=graalversion::$(python3 -c 'from xml.etree import ElementTree; print(ElementTree.parse("pom.xml").find(".//xmlns:graalvm.version", {"xmlns" : "http://maven.apache.org/POM/4.0.0"}).text)')"
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: ${{ steps.getgraalversion.outputs.graalversion }}
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'
      - name: Install native-image component
        run: |
          gu install native-image
      - name: Install Streamblocks-Tycho if not present
        if: steps.mavencache.outputs.cache-hit != 'true'
        run: |
          git clone --depth=1 https://github.com/streamblocks/streamblocks-tycho/
          cd streamblocks-tycho
          mvn -DskipTests install
          cd ..
      - name: Run build
        run: mvn --batch-mode --update-snapshots verify
      - name: Upload calnative
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: calnative
          # A file, directory or wildcard pattern that describes what to upload
          path: native/calnative
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
